# version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    expose:
      - "${DB_PORT}"
    networks:
      - ecommerce
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --skip-host-cache --skip-name-resolve
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - ecommerce
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NGROK_URL=${NGROK_URL}
    depends_on:
      mysql:
        condition: service_healthy

  ngrok:
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: ["ngrok", "http", "8080"]
    networks:
      - ecommerce
    ports:
      - "4040:4040"

  fe:
    build:
      context: .
      dockerfile: fe/Dockerfile
    ports:
      - "3000:80"
    networks:
      - ecommerce
    depends_on:
      - be

networks:
  ecommerce:
    driver: bridge

volumes:
  mysql-data:
